// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'button': string;
  'input': string;
  'page': string;
  'results': string;
}
export const cssExports: CssExports;
export default cssExports;
